name: Deploy to Vercel

on:
  push:
    branches:
      - master  # atau ganti 'main' ke 'master' jika branch kamu master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

        run: vercel --prod --token $VERCEL_TOKEN --yes
